### PR TITLE
Update Export URLs

### PR DESCRIPTION
**Pull request by ignBiometrical**

### CODE REVIEW

**Review by Decencies — APPROVED** [review]
+1

**Review by Xyphyn — APPROVED** [review]
Please

**Comment by HausemasterIssue** [comment]
Shouldn't those URL's be HTTPS instead of HTTP?

**Comment by ignBiometrical** [comment]
Nope, just double checked and it is HTTP, I am unsure if HTTPS integration is setup.

**Comment by HausemasterIssue** [comment]
@ignBiometrical When I run the program with your commits on my computer, it says it cannot download or find the file. Also, my skin won't load in Minecraft because it cannot download it from the Mojang servers (unrelated). It could possibly be because my computer blocks HTTP or the firewall is incorrectly setup, can you confirm it does work?

**Review by SIMULATAN — APPROVED** [review]
100% no virus confirmed

**Comment by egold555** [comment]
I've finally found some time to update the program. You can download the new version here: https://github.com/egold555/ReplaceModsWithForgeCSVMappingsGUI/raw/master/Releases/ReplaceModsWithForgeCSVMappingsGUI%20v1.2.jar

**Comment by SIMULATAN** [comment]
You're supposed to merge it, not close

**Comment by egold555** [comment]
> You're supposed to merge it, not close

No use pulling when ive implemented the changes already.. my bad

**Pull request closed without merging**
